name: Build and Deploy Docker Image

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        #monkey

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask prometheus_client

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myflaskapp:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your_server_ip << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/myflaskapp:latest
            docker stop myflaskapp || true
            docker rm myflaskapp || true
            docker run -d --name myflaskapp -p 5000:5000 -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/myflaskapp:latest
          EOF